# Generated by Django 3.0.4 on 2020-03-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='certification',
            field=models.ImageField(blank=True, upload_to='certifications'),
        ),
    ]
