# Generated by Django 3.0.4 on 2020-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0002_person_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='certification',
            field=models.ImageField(blank=True, default='certificate.pdf', upload_to='certifications'),
        ),
    ]
