# Generated by Django 3.0.4 on 2020-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0006_auto_20200329_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
    ]
