# Generated by Django 3.0.4 on 2020-03-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0007_auto_20200329_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterField(
            model_name='person',
            name='medium_name',
            field=models.CharField(max_length=30, verbose_name='الاسم الأوسط'),
        ),
    ]
