# Generated by Django 3.0.4 on 2020-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0009_auto_20200329_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='medium_name',
        ),
        migrations.AddField(
            model_name='person',
            name='w_name',
            field=models.CharField(default='Full name', max_length=60, verbose_name='Full name'),
        ),
    ]
