# Generated by Django 3.0.4 on 2020-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0010_auto_20200329_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='w_name',
            field=models.CharField(default='', max_length=60, verbose_name='Full name'),
        ),
    ]
