# Generated by Django 3.0.4 on 2020-03-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0012_auto_20200330_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
