# Generated by Django 3.0.4 on 2020-03-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0013_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='D:\\nshama\\certi\\images/test.jpeg', upload_to='')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='printcerti.Person')),
            ],
        ),
    ]
