# Generated by Django 3.0.4 on 2020-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0014_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='w_name',
            field=models.CharField(default='', max_length=22, verbose_name='اسمك الكامل'),
        ),
    ]
