# Generated by Django 3.0.4 on 2020-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0016_auto_20200401_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='w_name',
            field=models.CharField(default='', max_length=60, verbose_name='اسمك الكامل'),
        ),
    ]
