# Generated by Django 3.0.4 on 2020-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printcerti', '0017_auto_20200401_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='D:\\nshama\\certi\\images/test.jpeg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
